name: Deployment Security MS WEB

on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2

        - name: Setup Env Node
          uses: actions/setup-node@v1
          with:
              node-version: 19

        - name: Instalando lib package.json
          run: npm ci

        - name: Iniciando Build
          run: npm run build

        - name: Sync Files
          uses: SamKirkland/FTP-Deploy-Action@4.3.3
          with:
              server: ${{ secrets.FTP_HOST }}
              username: ${{ secrets.FTP_USER }}
              password: ${{ secrets.FTP_PWD }}
              port: ${{ secrets.FTP_PORT }}
              server-dir: public_html/