name: Deployment Security MS WEB

on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest

        environment: 
        name: production
        url: https://github.com

        steps:
        - uses: actions/checkout@v2

        - name: Setup Env Node
          uses: actions/setup-node@v1
          with:
              node-version: 19

        - name: Instalando lib package.json
          run: npm ci

        - name: Iniciando teste
          run: npm run test